export default {
    // ── Existing landing page keys ──────────────────────────────────────────
    home: "Home",
    settings: "Settings",
    welcome_message: "Welcome to RentFLO",
    login: "Login",
    dashboard: "Dashboard",
    tenant: "Tenant",
    owner: "Owner",
    admin: "Admin",
    properties: "Properties",
    payments: "Payments",
    support: "Support",
    logout: "Logout",
    never_chase_rent: "NEVER CHASE RENT.",
    we_pay_your_rent: "We pay your rent on the 1st.",
    your_tenant_pays_later: "Your tenant pays us later.",
    zero_friction: "Zero friction.",
    get_started: "GET STARTED",
    view_demo: "VIEW DEMO",
    terms: "Terms of Service",
    privacy: "Privacy Policy",
    refund: "Cancellation & Refund",
    contact_support: "Contact Support",
    usp_1_title: "Get Your Rent on Time",
    usp_1_desc: "Rent credited on the 1st, every month.",
    usp_2_title: "Zero Risk",
    usp_2_desc: "You get paid even if the tenant delays or leaves.",
    usp_3_title: "Easy Repairs & Maintenance",
    usp_3_desc: "We manage repairs from start to finish.",
    usp_4_title: "No Tenant Chasing",
    usp_4_desc: "We handle all follow-ups and disputes for you.",

    // ── Navigation ──────────────────────────────────────────────────────────
    nav_admin_console: "Admin Console",
    nav_maintenance: "Maintenance",
    nav_owner_portal: "Owner Portal",
    nav_tenant_dashboard: "Tenant Dashboard",
    nav_ledger: "Ledger",
    nav_kyc: "KYC Verification",
    nav_agreement: "Agreement",
    nav_sign_out: "Sign Out",

    // ── Legal Footer ────────────────────────────────────────────────────────
    footer_refund: "Cancellation/Refund Policy",

    // ── KYC Banner (shared) ─────────────────────────────────────────────────
    kyc_banner_in_progress: "Verification in Progress",
    kyc_banner_complete: "Complete KYC Verification",
    kyc_banner_reviewing: "Your documents are being reviewed. This usually takes 1-2 business days.",
    kyc_banner_verify_owner: "Verify your identity to add properties and receive rent advances.",
    kyc_banner_verify_tenant: "Verify your identity to make rent payments.",
    kyc_banner_button: "Complete KYC",

    // ── Onboarding ──────────────────────────────────────────────────────────
    onboarding_subtitle: "The future of rent management. Tell us who you are.",
    onboarding_iam_landlord: "I AM A LANDLORD",
    onboarding_landlord_desc: "Receive rent advances upfront",
    onboarding_iam_tenant: "I AM A TENANT",
    onboarding_tenant_desc: "Pay rent in flexible installments",
    onboarding_role_later: "You can change your role later in settings",
    onboarding_owner_next_step: "Let's set up your first property.",
    onboarding_tenant_next_step: "Find your home and start paying rent.",
    onboarding_role_error: "Failed to set your role. Please try again.",
    generic_error_title: "Error",

    // ── Setup ───────────────────────────────────────────────────────────────
    setup_landlord_badge: "Landlord Setup",
    setup_tenant_badge: "Tenant Setup",
    setup_owner_heading: "Add your property.",
    setup_tenant_heading: "Find your home.",
    setup_owner_subtitle: "Enter your property details to start receiving rent advances.",
    setup_tenant_subtitle: "Search by your landlord's email to link your account to your home.",
    setup_property_address: "Property Address",
    setup_property_address_placeholder: "e.g. 42 MG Road, Bangalore 560001",
    setup_monthly_rent: "Monthly Rent (₹)",
    setup_monthly_rent_placeholder: "e.g. 20000",
    setup_payout_day: "Payout Day (1–28)",
    setup_payout_day_placeholder: "1",
    setup_tenant_email: "Tenant Email",
    setup_tenant_email_placeholder: "tenant@email.com",
    setup_landlord_email_placeholder: "landlord@email.com",
    setup_tenant_email_optional: "optional — invite your tenant",
    setup_submit: "Set Up Property",
    setup_skip: "Skip for now",
    setup_landlord_email: "Landlord's Email Address",
    setup_available_properties: "Available Properties",
    setup_join: "Join",
    setup_all_set: "You're all set!",
    setup_redirecting: "Redirecting to your dashboard…",
    setup_month: "month",
    setup_payout_day_label: "Payout day",
    setup_owner_address_required: "Address required",
    setup_owner_rent_invalid: "Enter a valid monthly rent",
    setup_owner_payout_invalid: "Payout day must be between 1 and 28",
    setup_property_added: "Property added!",
    setup_property_ready_desc: "Your property and rent cycle are set up.",
    setup_property_failed: "Failed to add property",
    setup_tenant_email_required: "Enter your landlord's email",
    setup_no_properties_found: "No properties found",
    setup_no_vacant_properties: "No available (vacant) properties for that landlord.",
    setup_search_failed: "Search failed",
    setup_join_success: "Success",
    setup_join_success_desc: "You're linked to this property.",

    // ── Owner Dashboard ─────────────────────────────────────────────────────
    owner_title: "Owner Portal",
    owner_subtitle: "Welcome back. Your portfolio overview.",
    owner_add_property: "Add New Property",
    owner_add_kyc_required: "Add Property (KYC Required)",
    owner_rent_credited: "RENT CREDITED",
    owner_awaiting_payout: "AWAITING PAYOUT",
    owner_payout_status: "Payout Status",
    owner_credited_on: "Credited to your bank account on",
    owner_active_properties: "Active Properties",
    owner_recent_activity: "Recent Activity",
    owner_rent_advanced: "Rent Advanced",
    owner_pending_advance: "Pending Advance",
    owner_no_activity: "No recent activity.",
    owner_due_day: "Due Day:",
    owner_open: "Open",
    owner_resolved: "Resolved",
    owner_property_health: "Property Health",
    owner_paid_badge: "Paid",
    owner_pending_badge: "Pending",
    modal_add_property: "Add Property",
    modal_monthly_rent: "Monthly Rent (₹)",
    modal_payout_day: "Payout Day",
    modal_tenant_email_optional: "Tenant Email (Optional)",
    modal_tenant_email_hint: "Enter your tenant's email to link them to this property",
    modal_submit_property: "Add Property",

    // ── Tenant Dashboard ────────────────────────────────────────────────────
    tenant_title: "Tenant Dashboard",
    tenant_secure_pay: "RentFLO Secure Pay",
    tenant_manage_stay: "Manage your stay at",
    tenant_your_residence: "your residence",
    tenant_monthly_rent: "Monthly Rent",
    tenant_settlement_progress: "Settlement Progress",
    tenant_settled: "Settled",
    tenant_paid: "Paid:",
    tenant_remaining: "Remaining:",
    tenant_payment_history: "Payment History",
    tenant_payment_heading: "Payment",
    tenant_choose_method: "Choose your payment method.",
    tenant_flexible: "Flexible",
    tenant_full_only: "Full Only",
    tenant_amount_to_pay: "Amount to Pay (₹)",
    tenant_full_payment_amount: "Full payment amount",
    tenant_bank_security: "Protected by Bank-Grade Security",
    tenant_recent_activity: "Recent Activity",
    tenant_split_payment: "Split Payment",
    tenant_payment_pending: "Payment Pending",
    tenant_payment_failed: "Payment Failed",
    tenant_maintenance: "Maintenance",
    tenant_cancel: "Cancel",
    tenant_request_fix: "Request Fix",
    tenant_issue_title: "Issue Title",
    tenant_description: "Description",
    tenant_photo_proof: "Photo Proof (Optional)",
    tenant_upload_photo: "Upload Photo",
    tenant_photo_attached: "Photo attached",
    tenant_submit_request: "Submit Request",
    tenant_join_home: "Join My Home",
    tenant_join_home_subtitle: "Link yourself to a property by searching your landlord's email.",
    tenant_landlord_email: "Landlord Email",
    tenant_search: "Search",
    tenant_available_properties: "Available Properties",
    tenant_rent_label: "Rent:",
    tenant_per_month: "/month",
    tenant_join: "Join",
    tenant_no_active_rent: "No Active Rent",
    tenant_no_active_rent_desc: "Once you join a property, your rent payments will appear here.",
    tenant_full_prefix: "Full:",

    // ── Admin Dashboard ─────────────────────────────────────────────────────
    admin_title: "Admin Dashboard",
    admin_system_status: "System status:",
    admin_operational: "Operational",
    admin_download_audit: "Download Audit Log",
    admin_tab_overview: "Financial Overview",
    admin_tab_kyc: "KYC Approvals",
    admin_tab_users: "All Users",
    admin_total_exposure: "Total Exposure",
    admin_advanced: "Advanced",
    admin_collected: "Collected",
    admin_exposure_subtitle: "Advanced to Owners − Collected from Tenants",
    admin_total_advanced: "Total Advanced",
    admin_total_collected: "Total Collected",
    admin_pending_payouts: "Pending Payouts",
    admin_active_properties: "Active Properties",
    admin_capital_deployed: "Capital deployed to owners",
    admin_revenue_recovered: "Revenue recovered from tenants",
    admin_actions_required: "Actions required immediately",
    admin_priority_high: "Priority: High",
    admin_no_pending_payouts: "No pending payouts required.",
    admin_liquidity_ratio: "Liquidity Ratio",
    admin_liquidity_desc: "Comparison of deployed capital vs collected revenue.",
    admin_all_properties: "All Properties",
    admin_total_label: "Total",
    admin_property_address: "Property Address",
    admin_monthly_rent: "Monthly Rent",
    admin_owner_id: "Owner ID",
    admin_occupancy: "Occupancy",
    admin_occupied: "Occupied",
    admin_vacant: "Vacant",
    admin_no_properties: "No properties registered yet.",
    admin_pending_kyc: "Pending KYC Verifications",
    admin_no_kyc: "No pending KYC verifications.",
    admin_users_title: "All Users",
    admin_name: "Name",
    admin_email: "Email",
    admin_role: "Role",
    admin_kyc_status: "KYC Status",
    admin_verified: "Verified",
    admin_pending: "Pending",
    admin_not_submitted: "Not Submitted",
    admin_verify_user: "Verify User",
    admin_no_role: "NO ROLE",
    admin_mark_paid: "Confirm & Mark Paid",
    admin_net_transfer: "Net Transfer",
    admin_platform_fee: "Platform Fee (5%)",
    admin_confirm_amount: "Confirm Amount",
    admin_bank_receipt: "Bank Transfer Receipt",
    admin_receipt_hint: "Upload screenshot of bank transfer as proof of payment.",
    admin_stat_properties_sub: "Currently managed portfolio",
    admin_kyc_pan: "PAN",
    admin_kyc_aadhaar: "Aadhaar",
    admin_kyc_bank: "Bank A/C",
    admin_kyc_ifsc: "IFSC",
    admin_kyc_view_doc: "View ID Document",
    admin_kyc_view_cheque: "View Cancelled Cheque",
    admin_due_now: "DUE NOW",
    admin_net_payout: "Net Payout",
    admin_process_payout: "Process Payout",
    admin_confirm_transfer: "Confirm Manual Transfer",

    // ── Ledger ──────────────────────────────────────────────────────────────
    ledger_title: "Master Ledger",
    ledger_current_exposure: "Current Exposure",
    ledger_date: "Date",
    ledger_txn_id: "Txn ID",
    ledger_property: "Property",
    ledger_action: "Action",
    ledger_amount: "Amount",
    ledger_balance: "Balance",
    ledger_no_transactions: "No transactions recorded yet.",
    ledger_footer: "Bank-Grade Audit Trail • Real-Time Sync • Institutional Transparency",
    ledger_balance_label: "Balance:",

    // ── Admin Maintenance ───────────────────────────────────────────────────
    maint_title: "Maintenance Portal",
    maint_subtitle: "Manage all property maintenance requests.",
    maint_total: "Total",
    maint_open: "Open",
    maint_resolved: "Resolved",
    maint_open_requests: "Open Requests",
    maint_no_open: "No open maintenance requests.",
    maint_no_resolved: "No resolved tickets yet.",
    maint_date: "Date",
    maint_title_col: "Title",
    maint_property: "Property",
    maint_resolve: "Resolve",
    maint_view_photo: "View Photo",
    maint_click_close: "Click anywhere to close",

    // ── KYC Verify page ─────────────────────────────────────────────────────
    kyc_identity_badge: "Identity Verification",
    kyc_page_title: "KYC Verification",
    kyc_page_subtitle: "Complete your identity check to unlock all features.",
    kyc_verified_title: "KYC Verified",
    kyc_verified_desc: "Your identity has been verified. Next step: sign your tripartite agreement.",
    kyc_sign_agreement: "Sign Your Agreement",
    kyc_under_review_title: "Under Review",
    kyc_under_review_desc: "Your documents are being reviewed. This usually takes 1–2 business days.",
    kyc_identity_info: "Identity Information",
    kyc_full_legal_name: "Full Legal Name",
    kyc_name_placeholder: "As it appears on your ID document",
    kyc_id_type: "ID Type",
    kyc_choose_one: "(choose one)",
    kyc_pan_card: "PAN Card",
    kyc_aadhaar: "Aadhaar",
    kyc_pan_number: "PAN Number",
    kyc_pan_hint: "10-character alphanumeric (e.g. ABCDE1234F)",
    kyc_aadhaar_number: "Aadhaar Number",
    kyc_aadhaar_hint: "12-digit number on your Aadhaar card",
    kyc_upload_pan: "Upload PAN Card",
    kyc_upload_aadhaar: "Upload Aadhaar Card",
    kyc_doc_uploaded: "Document uploaded ✓",
    kyc_choose_file: "Choose file (image or PDF)",
    kyc_doc_ready: "Document ready for upload.",
    kyc_bank_details: "Bank Details",
    kyc_landlords_only: "(landlords only)",
    kyc_account_number: "Account Number",
    kyc_account_placeholder: "Enter account number",
    kyc_ifsc_code: "IFSC Code",
    kyc_cancelled_cheque: "Cancelled Cheque",
    kyc_uploaded_tick: "Uploaded ✓",
    kyc_upload_cheque: "Upload cheque",
    kyc_submitting: "Submitting…",
    kyc_submit: "Submit for Verification",

    // ── Agreement page ──────────────────────────────────────────────────────
    agr_badge: "Tripartite Agreement",
    agr_title: "Sign Your Agreement",
    agr_subtitle: "Read the full agreement below, then draw your signature to execute it digitally.",
    agr_no_property: "No property found. Please complete your property setup first.",
    agr_go_to_setup: "Go to Setup",
    agr_signed_title: "Agreement Signed",
    agr_signed_desc: "Your digital signature has been recorded on the RentFLO ledger.",
    agr_both_signed: " Both parties have signed — the agreement is fully executed.",
    agr_waiting_other: " Waiting for the other party to sign.",
    agr_go_to_dashboard: "Go to Dashboard",
    agr_scroll_hint: "↓ Scroll to read the full agreement before signing",
    agr_your_signature: "Your Digital Signature",
    agr_read_to_unlock: "Read the full agreement above to unlock the signature pad.",
    agr_recording: "Recording your signature…",
    agr_draw_here: "Draw your signature here",
    agr_clear: "Clear",
    agr_confirm_signature: "Confirm Signature",
    agr_rentflo_party: "RentFLO",
    agr_landlord_party: "Landlord",
    agr_tenant_party: "Tenant",
    agr_signed_tick: "✓ Signed",
    agr_pending: "Pending",
    agr_rent_advance: "Rent Advance Agreement",

    // ── Bottom Navigation ───────────────────────────────────────────────────
    nav_home: "Home",
    nav_repairs: "Repairs",
    nav_messages: "Messages",
    nav_profile: "Profile",
    nav_inbox: "Inbox",
    nav_admin_short: "Admin",
    nav_kyc_short: "KYC",

    // ── AI Chatbot ──────────────────────────────────────────────────────────
    chat_assistant_title: "RentFLO Assistant",
    chat_assistant_subtitle: "AI · Powered by Replit",
    chat_how_help: "How can I help you?",
    chat_ask_anything: "Ask me anything about your rent, KYC, or payments.",
    chat_placeholder: "Ask about rent, KYC, payments…",
    chat_disclaimer: "AI may make mistakes · Not financial advice",
    chat_thinking: "Thinking…",
    chat_error: "Sorry, something went wrong. Please try again.",
    chat_clear: "Clear",
    chat_live: "Live",
    chat_talk_to_live: "Talk to a Live Agent",
    chat_need_human: "Need a human? Open a chat with our support team.",
    chat_suggestion_1: "What does EXPOSED status mean?",
    chat_suggestion_2: "How do I complete my KYC?",
    chat_suggestion_3: "How does rent advance work?",
    chat_suggestion_4: "How do I report a maintenance issue?",

    // ── Tenant Tabs / Stats / Empty States ──────────────────────────────────
    tab_overview: "Overview",
    tab_payments: "Payments",
    tab_lease: "Lease",
    stat_due_in: "Due In",
    stat_paid_ytd: "Paid YTD",
    getting_started: "Getting Started",
    of_completed: "completed",
    step_join_property: "Join a property",
    step_complete_kyc: "Complete KYC verification",
    step_sign_agreement: "Sign the rental agreement",
    step_first_payment: "Make your first payment",
    current_month: "Current Month",
    settlement_progress_label: "Settlement Progress",
    settled_suffix: "Settled",
    paid_label: "Paid",
    remaining_label: "Remaining",
    pay_now: "Pay Now",
    this_month_settled: "This month is fully settled",
    recent_payments: "Recent Payments",
    view_all: "View All",
    payment_received: "Payment Received",
    awaiting_verification: "Awaiting Verification",
    pending_label: "Pending",
    failed_label: "Failed",
    verifying_label: "VERIFYING",
    all_months: "All Months",
    no_payment_history: "No payment history yet.",
    settled_count_suffix: "settled",
    payments_empty_no_property: "Join a property from the Overview tab to start making rent payments.",
    lease_empty_no_property: "You haven't joined a property yet. Find your home from the Overview tab to view lease details.",
    property_details: "Property Details",
    address_label: "Address",
    payment_due: "Payment Due",
    of_every_month: "of every month",
    agreement_status_label: "Agreement Status",
    agreement_created: "Agreement Created",
    owner_signed_step: "Owner Signed",
    tenant_signed_step: "Tenant Signed",
    fully_executed: "Fully Executed",
    view_sign_agreement: "View / Sign Agreement",
    kyc_verification_label: "KYC Verification",
    identity_verified: "Identity Verified",
    under_review: "Under Review",
    not_submitted: "Not Submitted",
    cleared_to_pay: "You're cleared to make payments.",
    required_to_process: "Required to process rent payments.",
    check_kyc_status: "Check KYC Status",
    complete_kyc_now: "Complete KYC Now",
    maintenance_requests: "Maintenance Requests",
    no_requests_yet: "No requests yet",
    open_label: "open",
    total_label: "total",
    payment_successful: "Payment Successful",
    open_request_singular: "open maintenance request",
    open_request_plural: "open maintenance requests",
    tap_view_status: "Tap to view status",
    join_property_btn: "Join Property",
    or_pay_directly: "Or pay directly via",
    pay_via_gpay: "Pay via GPay",
    pay_via_phonepe: "Pay via PhonePe",
    any_upi_app: "Any UPI App →",
    full_prefix: "Full",
    max_prefix: "Max",
    step_verify_identity: "Verify Identity",
    step_sign_agreement_short: "Sign Agreement",
    step_pay_rent: "Pay Rent",
    status_settled: "Settled",
    status_exposed: "Exposed",
    status_arrears: "Arrears",
    chat_floating_label: "Chat",
    per_month: "/ month",
    chat_open_aria: "Open AI assistant",
    chat_close_aria: "Close chat",
    chat_send_aria: "Send message",
    chat_live_title: "Talk to a live agent",
    didit_title: "Instant E-KYC with Didit",
    didit_subtitle: "Verify your identity in under a minute. Government-grade ID checks powered by Didit.",
    didit_button: "Verify with Didit",
    didit_opening: "Opening Didit…",
    didit_redirect_note: "You'll be sent to Didit and brought right back to RentFLO when done.",
    nav_alerts: "Alerts",
    nav_terms_short: "Terms",
    nav_privacy_short: "Privacy",
    nav_refund_short: "Refund",
    nav_support_short: "Support",
    nav_messages: "Messages",
    agr_subtitle_leegality: "Read the full agreement below, then execute it with a legally valid Aadhaar e-sign via Leegality.",
    agr_download_pdf: "Download PDF",
    agr_awaiting_esign: "Awaiting E-Signature",
    agr_esign_sent_desc: "The agreement has been sent for e-signing via Leegality. Check your email or phone for the signing link.",
    agr_esign_auto_update: "This page will update automatically once all parties have signed.",
    agr_esign_via_leegality: "E-Sign via Leegality",
    agr_esign_read_desc: "Read the full agreement above, then click below to execute it with a legally valid Aadhaar e-sign through Leegality.",
    agr_sending: "Sending\u2026",
    agr_send_for_esign: "Send for E-Sign",
    agr_scroll_first: "Scroll to Read Agreement First",
    agr_leegality_tagline: "\u00b7 Legally Valid E-Sign \u00b7 IT Act 2000",
    maint_badge: "Maintenance",
    maint_page_title: "Repairs & Maintenance",
    maint_tenant_subtitle: "Report issues and track repair progress.",
    maint_owner_subtitle: "View maintenance requests for your properties.",
    maint_admin_subtitle: "Manage all maintenance tickets across properties.",
    maint_new_request: "New Request",
    maint_cancel_btn: "Cancel",
    maint_form_heading: "New Maintenance Request",
    maint_property_label: "Property",
    maint_select_property: "Select a property\u2026",
    maint_issue_title_label: "Issue Title",
    maint_description_label: "Description",
    maint_photo_optional: "Photo (optional)",
    maint_upload_photo_btn: "Upload photo",
    maint_submit_request: "Submit Request",
    maint_tab_active: "Active",
    maint_no_active: "No active requests \u2014 all clear.",
    maint_ticket_submitted: "Ticket submitted",
    maint_ticket_sent: "Your maintenance request has been sent.",
    maint_photo_btn: "Photo",
    maint_resolve_btn: "Resolve",
    maint_resolved_on: "Resolved",
    maint_file_too_large: "File too large",
    maint_file_max: "Max photo size is 5MB.",
    maint_select_property_toast: "Select a property",
    maint_enter_title_toast: "Enter a title",
    maint_describe_issue_toast: "Describe the issue",
    bell_notifications: "Notifications",
    bell_push_on: "On",
    bell_push_off: "Off",
    bell_push_na: "N/A",
    bell_push_blocked: "Blocked",
    bell_no_notifications: "No notifications yet",
    bell_mark_all_read: "Mark all read",
    bell_type_rent_advanced: "Rent Advanced",
    bell_type_rent_collected: "Payment Received",
    bell_type_maint_created: "Maintenance Request",
    bell_type_maint_resolved: "Issue Resolved",
    bell_type_rent_due: "Rent Due",
    messages_heading: "Messages",
    messages_no_properties: "No properties linked to your account yet.",
    messages_tenant_thread: "Tenant thread",
    messages_landlord_thread: "Landlord thread",
    messages_select_property: "Select a property to start messaging",
    messages_private_thread: "Private thread",
    messages_no_msgs_tenant: "No messages yet. Say hello to your tenant.",
    messages_no_msgs_landlord: "No messages yet. Say hello to your landlord.",
    messages_failed_send: "Failed to send. Please try again.",
    messages_placeholder_tenant: "Message your tenant\u2026",
    messages_placeholder_landlord: "Message your landlord\u2026",
    messages_enter_hint: "Enter to send \u00b7 Shift+Enter for new line",
    messages_role_tenant: "Tenant",
    messages_role_landlord: "Landlord",
    admin_conv_heading: "All Conversations",
    admin_conv_subtitle: "Admin oversight",
    admin_conv_no_convs: "No conversations yet",
    admin_conv_no_convs_desc: "Messages between owners and tenants will appear here.",
    admin_conv_read_only: "Read Only",
    admin_conv_compliance: "Admin view \u2014 visible for compliance and dispute resolution only.",
    admin_conv_no_msgs: "No messages in this conversation yet.",
    admin_conv_owner: "Owner",
    admin_conv_tenant: "Tenant",
    admin_conv_select: "Select a conversation to view",
    admin_conv_read: "Read",
    profile_account_label: "Account",
    profile_title: "Profile",
    profile_full_name: "Full Name",
    profile_edit: "Edit",
    profile_first_name: "First Name",
    profile_last_name: "Last Name",
    profile_save: "Save",
    profile_cancel: "Cancel",
    profile_email: "Email",
    profile_login_provider: "Managed by your login provider",
    profile_kyc_status: "KYC Status",
    profile_verified: "Verified",
    profile_under_review: "Under Review",
    profile_not_submitted: "Not Submitted",
    profile_legal_name: "Legal Name (KYC)",
    profile_footer: "RentFLO \u00b7 Secured Platform \u00b7 rentflo.com",
    profile_role_tenant: "Tenant",
    profile_role_owner: "Property Owner",
    profile_role_admin: "Administrator",
    profile_updated: "Profile Updated",
    profile_name_saved: "Your name has been saved.",
    notif_inbox: "Inbox",
    notif_title: "Notifications",
    notif_mark_all_read: "Mark all read",
    notif_empty: "No notifications yet",
    notif_empty_desc: "We'll notify you about rent, repairs, and more",
    landing_rent_platform: "Rent Payment Platform",
    landing_log_in: "Log In",
    landing_bank_grade: "Bank-Grade Security",
    landing_instant_payout: "Instant Payout",
    landing_monthly_rent_label: "Monthly Rent",
    landing_guaranteed_payout: "Guaranteed Payout",
    landing_settlement_label: "Settlement",
    landing_settlement_progress: "Settlement Progress",
    landing_0_settled: "0% Settled",
    landing_rent_guaranteed: "Rent Guaranteed",
    landing_live: "Live",
    landing_how_it_works: "How it works",
    landing_rent_now: "Rent Now,",
    landing_pay_later: "Pay Later.",
    landing_owner_tagline: "Full rent. Zero chasing.",
    landing_tenant_tagline: "Pay your way. No pressure.",
    landing_for_owners: "For Owners",
    landing_for_tenants: "For Tenants",
    landing_owner_pay_full: "We pay your full rent upfront in a lump sum \u2014 and collect from your tenants ourselves.",
    landing_tenant_pay_back: "Tenants pay us back in flexible monthly or weekly payments \u2014 on their schedule.",
    landing_why_rentflo: "Why RentFLO",
    landing_built_for_landlords: "Built for landlords who demand certainty.",
    landing_who_its_for: "Who it's for",
    landing_what_you_get: "What you get",
    landing_how_helps: "How it helps you",
    landing_owner_b1_title: "Lump-sum on the 1st",
    landing_owner_b1_desc: "Full month's rent hits your account on the first \u2014 every month, on time.",
    landing_owner_b2_title: "We collect from tenants",
    landing_owner_b2_desc: "RentFLO handles all tenant follow-ups, reminders, and repayment collection.",
    landing_owner_b3_title: "Zero vacancy risk",
    landing_owner_b3_desc: "Rent keeps flowing even during tenant transitions or late payments.",
    landing_owner_b4_title: "Real-time dashboard",
    landing_owner_b4_desc: "Track every property's status, payouts, and settlement progress in one place.",
    landing_tenant_b1_title: "Rent paid on your behalf",
    landing_tenant_b1_desc: "Your landlord gets paid in full \u2014 no late fees, no awkward conversations.",
    landing_tenant_b2_title: "Weekly or monthly plans",
    landing_tenant_b2_desc: "Split your rent into manageable instalments that match your pay cycle.",
    landing_tenant_b3_title: "No large lump sum needed",
    landing_tenant_b3_desc: "Move in without draining your savings \u2014 spread the cost over time.",
    landing_tenant_b4_title: "Build a payment history",
    landing_tenant_b4_desc: "Consistent repayments help you build a reliable financial track record.",
    landing_faq_eyebrow: "FAQ",
    landing_faq_title: "Frequently Asked Questions",
    landing_faq_q1: "What does it mean to split rent payments?",
    landing_faq_a1: "RentFLO advances the full rent to your landlord on the 1st of each month. You then repay that amount in smaller instalments across the month \u2014 weekly or bi-weekly \u2014 so your cash flow stays healthy.",
    landing_faq_q2: "How can I pay my rent using flexible payment options?",
    landing_faq_a2: "Once you're onboarded as a tenant on RentFLO, you can choose how many instalments to split your rent into. Payments are made securely via Cashfree using UPI, cards, or net banking.",
    landing_faq_q3: "Are there extra fees when I split my rent?",
    landing_faq_a3: "RentFLO charges a small platform fee for the advance service. There are no hidden charges. The fee is shown clearly before you confirm your payment plan.",
    landing_faq_q4: "Can I use credit to cover rent payments?",
    landing_faq_a4: "Yes. RentFLO acts as the credit bridge between you and your landlord. We advance the full rent on your behalf, so you can pay it back when it suits you during the month.",
    landing_faq_q5: "Why choose flexible payment plans instead of traditional rent terms?",
    landing_faq_a5: "Traditional rent is due in one lump sum \u2014 often right after payday gaps. RentFLO's flexible plans align your rent payments with your income schedule, reducing financial stress without involving your landlord.",
    landing_bank_grade_encryption: "Bank-Grade Encryption",
    owner_due_day_prefix: "Due day",
    owner_manage: "Manage",
    owner_live: "LIVE",
    modal_add_property_subtitle: "Add a new property to your portfolio",
    processing: "Processing\u2026",
    owner_last_payout: "LAST PAYOUT",
    owner_payout_status_label: "PAYOUT STATUS",
    owner_add_property_start: "Add a property and complete verification to start receiving payouts.",
    owner_payout_collected: "Collected:",
    owner_kpi_total_advanced: "Total Advanced",
    owner_kpi_lifetime: "lifetime",
    owner_kpi_collected: "Collected",
    owner_kpi_from_tenants: "from tenants",
    owner_kpi_net_exposure: "Net Exposure",
    owner_kpi_outstanding: "outstanding",
    owner_kpi_collection_rate: "Collection Rate",
    owner_kpi_excellent: "Excellent",
    owner_kpi_good: "Good",
    owner_kpi_needs_attention: "Needs attention",
    owner_chart_title: "Monthly Collection History",
    owner_chart_advanced: "ADVANCED",
    owner_chart_collected: "COLLECTED",
    owner_months_settled: "month(s) fully settled",
    owner_no_properties_yet: "No properties yet",
    owner_add_first_property: "Add your first property to get started",
    owner_view_all: "View all",
    owner_portal_label: "OWNER PORTAL",
    step_collect_rent: "Collect Rent",
    admin_tab_verifications: "Verifications",
    admin_verif_heading: "Manual Payment Verifications",
    admin_verif_subtitle: "Match the UTR against your bank statement before approving.",
    admin_verif_pending: "PENDING VERIFICATION",
    admin_verif_amount: "Amount",
    admin_verif_utr: "UTR / Reference",
    admin_verif_submitted: "Submitted",
    admin_verif_tab: "Verifications",
    admin_verif_view_screenshot: "View screenshot",
    admin_verif_verify: "Verify",
    admin_verif_reject: "Reject",
    admin_verif_no_payments: "No payments awaiting verification.",
    processing_text: "Processing…",
    admin_payment_verified_title: "Payment Verified",
    admin_payment_verified_desc: "Ledger has been credited.",
    admin_payment_rejected_title: "Payment Rejected",
    admin_payment_rejected_desc: "Tenant has been notified.",
    admin_no_data: "No Data",
    admin_no_transactions: "No transactions to export.",
    admin_receipt_uploaded: "Receipt uploaded",
    admin_receipt_ready: "Ready for submission",
    admin_upload_screenshot: "Click to upload bank transfer screenshot",
    pay_rent_did_complete: "Did you complete the payment?",
    verify_or_manual: "Or verify manually",
    support_email_label: "Email Support",
    support_phone_label: "Phone Support",
    support_hours_label: "Business Hours",
    support_escalation: "Escalation",
    admin_payout_processed: "Payout Processed",
    admin_user_verified_title: "User Verified",
    admin_user_verified_desc: "KYC verification approved successfully.",
    admin_download_started: "Download Started",
    admin_download_started_desc: "Audit log CSV is being downloaded.",
    ledger_capital_advanced: "Capital Advanced",
    ledger_rent_collected: "Rent Collected",
    ledger_pending: "Pending",
    ledger_export: "Export",

};
