import { createContext, useContext, useState, useEffect, useCallback, ReactNode } from 'react';

const translations = {
  en: {
    // ── Existing landing page keys ──────────────────────────────────────────
    home: "Home",
    settings: "Settings",
    welcome_message: "Welcome to RentFLO",
    login: "Login",
    change_language: "Change Language",
    dashboard: "Dashboard",
    tenant: "Tenant",
    owner: "Owner",
    admin: "Admin",
    properties: "Properties",
    payments: "Payments",
    support: "Support",
    logout: "Logout",
    never_chase_rent: "NEVER CHASE RENT.",
    we_pay_your_rent: "We pay your rent on the 1st.",
    your_tenant_pays_later: "Your tenant pays us later.",
    zero_friction: "Zero friction.",
    get_started: "GET STARTED",
    view_demo: "VIEW DEMO",
    terms: "Terms of Service",
    privacy: "Privacy Policy",
    refund: "Cancellation & Refund",
    contact_support: "Contact Support",
    usp_1_title: "Get Your Rent on Time",
    usp_1_desc: "Rent credited on the 1st, every month.",
    usp_2_title: "Zero Risk",
    usp_2_desc: "You get paid even if the tenant delays or leaves.",
    usp_3_title: "Easy Repairs & Maintenance",
    usp_3_desc: "We manage repairs from start to finish.",
    usp_4_title: "No Tenant Chasing",
    usp_4_desc: "We handle all follow-ups and disputes for you.",

    // ── Navigation ──────────────────────────────────────────────────────────
    nav_admin_console: "Admin Console",
    nav_maintenance: "Maintenance",
    nav_owner_portal: "Owner Portal",
    nav_tenant_dashboard: "Tenant Dashboard",
    nav_ledger: "Ledger",
    nav_kyc: "KYC Verification",
    nav_agreement: "Agreement",
    nav_sign_out: "Sign Out",

    // ── Legal Footer ────────────────────────────────────────────────────────
    footer_refund: "Cancellation/Refund Policy",

    // ── KYC Banner (shared) ─────────────────────────────────────────────────
    kyc_banner_in_progress: "Verification in Progress",
    kyc_banner_complete: "Complete KYC Verification",
    kyc_banner_reviewing: "Your documents are being reviewed. This usually takes 1-2 business days.",
    kyc_banner_verify_owner: "Verify your identity to add properties and receive rent advances.",
    kyc_banner_verify_tenant: "Verify your identity to make rent payments.",
    kyc_banner_button: "Complete KYC",

    // ── Onboarding ──────────────────────────────────────────────────────────
    onboarding_subtitle: "The future of rent management. Tell us who you are.",
    onboarding_iam_landlord: "I AM A LANDLORD",
    onboarding_landlord_desc: "Receive rent advances upfront",
    onboarding_iam_tenant: "I AM A TENANT",
    onboarding_tenant_desc: "Pay rent in flexible installments",
    onboarding_role_later: "You can change your role later in settings",

    // ── Setup ───────────────────────────────────────────────────────────────
    setup_landlord_badge: "Landlord Setup",
    setup_tenant_badge: "Tenant Setup",
    setup_owner_heading: "Add your property.",
    setup_tenant_heading: "Find your home.",
    setup_owner_subtitle: "Enter your property details to start receiving rent advances.",
    setup_tenant_subtitle: "Search by your landlord's email to link your account to your home.",
    setup_property_address: "Property Address",
    setup_monthly_rent: "Monthly Rent (₹)",
    setup_payout_day: "Payout Day (1–28)",
    setup_tenant_email: "Tenant Email",
    setup_tenant_email_optional: "optional — invite your tenant",
    setup_submit: "Set Up Property",
    setup_skip: "Skip for now",
    setup_landlord_email: "Landlord's Email Address",
    setup_available_properties: "Available Properties",
    setup_join: "Join",
    setup_all_set: "You're all set!",
    setup_redirecting: "Redirecting to your dashboard…",
    setup_month: "month",
    setup_payout_day_label: "Payout day",

    // ── Owner Dashboard ─────────────────────────────────────────────────────
    owner_title: "Owner Portal",
    owner_subtitle: "Welcome back. Your portfolio overview.",
    owner_add_property: "Add New Property",
    owner_add_kyc_required: "Add Property (KYC Required)",
    owner_rent_credited: "RENT CREDITED",
    owner_awaiting_payout: "AWAITING PAYOUT",
    owner_payout_status: "Payout Status",
    owner_credited_on: "Credited to your bank account on",
    owner_active_properties: "Active Properties",
    owner_recent_activity: "Recent Activity",
    owner_rent_advanced: "Rent Advanced",
    owner_pending_advance: "Pending Advance",
    owner_no_activity: "No recent activity.",
    owner_due_day: "Due Day:",
    owner_open: "Open",
    owner_resolved: "Resolved",
    owner_property_health: "Property Health",
    owner_paid_badge: "Paid",
    owner_pending_badge: "Pending",
    // Add property modal
    modal_add_property: "Add Property",
    modal_monthly_rent: "Monthly Rent (₹)",
    modal_payout_day: "Payout Day",
    modal_tenant_email_optional: "Tenant Email (Optional)",
    modal_tenant_email_hint: "Enter your tenant's email to link them to this property",
    modal_submit_property: "Add Property",

    // ── Tenant Dashboard ────────────────────────────────────────────────────
    tenant_title: "Tenant Dashboard",
    tenant_secure_pay: "RentFLO Secure Pay",
    tenant_manage_stay: "Manage your stay at",
    tenant_your_residence: "your residence",
    tenant_monthly_rent: "Monthly Rent",
    tenant_settlement_progress: "Settlement Progress",
    tenant_settled: "Settled",
    tenant_paid: "Paid:",
    tenant_remaining: "Remaining:",
    tenant_payment_history: "Payment History",
    tenant_payment_heading: "Payment",
    tenant_choose_method: "Choose your payment method.",
    tenant_flexible: "Flexible",
    tenant_full_only: "Full Only",
    tenant_amount_to_pay: "Amount to Pay (₹)",
    tenant_full_payment_amount: "Full payment amount",
    tenant_bank_security: "Protected by Bank-Grade Security",
    tenant_recent_activity: "Recent Activity",
    tenant_split_payment: "Split Payment",
    tenant_payment_pending: "Payment Pending",
    tenant_payment_failed: "Payment Failed",
    tenant_maintenance: "Maintenance",
    tenant_cancel: "Cancel",
    tenant_request_fix: "Request Fix",
    tenant_issue_title: "Issue Title",
    tenant_description: "Description",
    tenant_photo_proof: "Photo Proof (Optional)",
    tenant_upload_photo: "Upload Photo",
    tenant_photo_attached: "Photo attached",
    tenant_submit_request: "Submit Request",
    tenant_join_home: "Join My Home",
    tenant_join_home_subtitle: "Link yourself to a property by searching your landlord's email.",
    tenant_landlord_email: "Landlord Email",
    tenant_search: "Search",
    tenant_available_properties: "Available Properties",
    tenant_rent_label: "Rent:",
    tenant_per_month: "/month",
    tenant_join: "Join",
    tenant_no_active_rent: "No Active Rent",
    tenant_no_active_rent_desc: "Once you join a property, your rent payments will appear here.",
    tenant_full_prefix: "Full:",

    // ── Admin Dashboard ─────────────────────────────────────────────────────
    admin_title: "Admin Dashboard",
    admin_system_status: "System status:",
    admin_operational: "Operational",
    admin_download_audit: "Download Audit Log",
    admin_tab_overview: "Financial Overview",
    admin_tab_kyc: "KYC Approvals",
    admin_tab_users: "All Users",
    admin_total_exposure: "Total Exposure",
    admin_advanced: "Advanced",
    admin_collected: "Collected",
    admin_exposure_subtitle: "Advanced to Owners − Collected from Tenants",
    admin_total_advanced: "Total Advanced",
    admin_total_collected: "Total Collected",
    admin_pending_payouts: "Pending Payouts",
    admin_active_properties: "Active Properties",
    admin_capital_deployed: "Capital deployed to owners",
    admin_revenue_recovered: "Revenue recovered from tenants",
    admin_actions_required: "Actions required immediately",
    admin_priority_high: "Priority: High",
    admin_no_pending_payouts: "No pending payouts required.",
    admin_liquidity_ratio: "Liquidity Ratio",
    admin_liquidity_desc: "Comparison of deployed capital vs collected revenue.",
    admin_all_properties: "All Properties",
    admin_total_label: "Total",
    admin_property_address: "Property Address",
    admin_monthly_rent: "Monthly Rent",
    admin_owner_id: "Owner ID",
    admin_occupancy: "Occupancy",
    admin_occupied: "Occupied",
    admin_vacant: "Vacant",
    admin_no_properties: "No properties registered yet.",
    admin_pending_kyc: "Pending KYC Verifications",
    admin_no_kyc: "No pending KYC verifications.",
    admin_users_title: "All Users",
    admin_name: "Name",
    admin_email: "Email",
    admin_role: "Role",
    admin_kyc_status: "KYC Status",
    admin_verified: "Verified",
    admin_pending: "Pending",
    admin_not_submitted: "Not Submitted",
    admin_verify_user: "Verify User",
    admin_no_role: "NO ROLE",
    // Pay owner modal
    admin_mark_paid: "Confirm & Mark Paid",
    admin_net_transfer: "Net Transfer",
    admin_platform_fee: "Platform Fee (5%)",
    admin_confirm_amount: "Confirm Amount",
    admin_bank_receipt: "Bank Transfer Receipt",
    admin_receipt_hint: "Upload screenshot of bank transfer as proof of payment.",
    // Additional admin keys
    admin_stat_properties_sub: "Currently managed portfolio",
    admin_kyc_pan: "PAN",
    admin_kyc_aadhaar: "Aadhaar",
    admin_kyc_bank: "Bank A/C",
    admin_kyc_ifsc: "IFSC",
    admin_kyc_view_doc: "View ID Document",
    admin_kyc_view_cheque: "View Cancelled Cheque",
    admin_due_now: "DUE NOW",
    admin_net_payout: "Net Payout",
    admin_process_payout: "Process Payout",
    admin_confirm_transfer: "Confirm Manual Transfer",

    // ── Ledger ──────────────────────────────────────────────────────────────
    ledger_title: "Master Ledger",
    ledger_current_exposure: "Current Exposure",
    ledger_date: "Date",
    ledger_txn_id: "Txn ID",
    ledger_property: "Property",
    ledger_action: "Action",
    ledger_amount: "Amount",
    ledger_balance: "Balance",
    ledger_no_transactions: "No transactions recorded yet.",
    ledger_footer: "Bank-Grade Audit Trail • Real-Time Sync • Institutional Transparency",
    ledger_balance_label: "Balance:",

    // ── Admin Maintenance ───────────────────────────────────────────────────
    maint_title: "Maintenance Portal",
    maint_subtitle: "Manage all property maintenance requests.",
    maint_total: "Total",
    maint_open: "Open",
    maint_resolved: "Resolved",
    maint_open_requests: "Open Requests",
    maint_no_open: "No open maintenance requests.",
    maint_no_resolved: "No resolved tickets yet.",
    maint_date: "Date",
    maint_title_col: "Title",
    maint_property: "Property",
    maint_resolve: "Resolve",
    maint_view_photo: "View Photo",
    maint_click_close: "Click anywhere to close",

    // ── KYC Verify page ─────────────────────────────────────────────────────
    kyc_identity_badge: "Identity Verification",
    kyc_page_title: "KYC Verification",
    kyc_page_subtitle: "Complete your identity check to unlock all features.",
    kyc_verified_title: "KYC Verified",
    kyc_verified_desc: "Your identity has been verified. Next step: sign your tripartite agreement.",
    kyc_sign_agreement: "Sign Your Agreement",
    kyc_under_review_title: "Under Review",
    kyc_under_review_desc: "Your documents are being reviewed. This usually takes 1–2 business days.",
    kyc_identity_info: "Identity Information",
    kyc_full_legal_name: "Full Legal Name",
    kyc_name_placeholder: "As it appears on your ID document",
    kyc_id_type: "ID Type",
    kyc_choose_one: "(choose one)",
    kyc_pan_card: "PAN Card",
    kyc_aadhaar: "Aadhaar",
    kyc_pan_number: "PAN Number",
    kyc_pan_hint: "10-character alphanumeric (e.g. ABCDE1234F)",
    kyc_aadhaar_number: "Aadhaar Number",
    kyc_aadhaar_hint: "12-digit number on your Aadhaar card",
    kyc_upload_pan: "Upload PAN Card",
    kyc_upload_aadhaar: "Upload Aadhaar Card",
    kyc_doc_uploaded: "Document uploaded ✓",
    kyc_choose_file: "Choose file (image or PDF)",
    kyc_doc_ready: "Document ready for upload.",
    kyc_bank_details: "Bank Details",
    kyc_landlords_only: "(landlords only)",
    kyc_account_number: "Account Number",
    kyc_account_placeholder: "Enter account number",
    kyc_ifsc_code: "IFSC Code",
    kyc_cancelled_cheque: "Cancelled Cheque",
    kyc_uploaded_tick: "Uploaded ✓",
    kyc_upload_cheque: "Upload cheque",
    kyc_submitting: "Submitting…",
    kyc_submit: "Submit for Verification",

    // ── Agreement page ──────────────────────────────────────────────────────
    agr_badge: "Tripartite Agreement",
    agr_title: "Sign Your Agreement",
    agr_subtitle: "Read the full agreement below, then draw your signature to execute it digitally.",
    agr_no_property: "No property found. Please complete your property setup first.",
    agr_go_to_setup: "Go to Setup",
    agr_signed_title: "Agreement Signed",
    agr_signed_desc: "Your digital signature has been recorded on the RentFLO ledger.",
    agr_both_signed: " Both parties have signed — the agreement is fully executed.",
    agr_waiting_other: " Waiting for the other party to sign.",
    agr_go_to_dashboard: "Go to Dashboard",
    agr_scroll_hint: "↓ Scroll to read the full agreement before signing",
    agr_your_signature: "Your Digital Signature",
    agr_read_to_unlock: "Read the full agreement above to unlock the signature pad.",
    agr_recording: "Recording your signature…",
    agr_draw_here: "Draw your signature here",
    agr_clear: "Clear",
    agr_confirm_signature: "Confirm Signature",
    agr_rentflo_party: "RentFLO",
    agr_landlord_party: "Landlord",
    agr_tenant_party: "Tenant",
    agr_signed_tick: "✓ Signed",
    agr_pending: "Pending",
    agr_rent_advance: "Rent Advance Agreement",
  },

  hi: {
    // ── Landing page ────────────────────────────────────────────────────────
    home: "होम",
    settings: "सेटिंग्स",
    welcome_message: "RentFLO में आपका स्वागत है",
    login: "लॉगिन",
    change_language: "भाषा बदलें",
    dashboard: "डैशबोर्ड",
    tenant: "किराएदार",
    owner: "मालिक",
    admin: "व्यवस्थापक",
    properties: "संपत्तियाँ",
    payments: "भुगतान",
    support: "सहायता",
    logout: "लॉगआउट",
    never_chase_rent: "किराए के पीछे कभी न भागें।",
    we_pay_your_rent: "हम पहली तारीख को आपका किराया देते हैं।",
    your_tenant_pays_later: "आपका किराएदार बाद में हमें भुगतान करता है।",
    zero_friction: "बिल्कुल आसान।",
    get_started: "शुरू करें",
    view_demo: "डेमो देखें",
    terms: "सेवा की शर्तें",
    privacy: "गोपनीयता नीति",
    refund: "रद्दीकरण और धनवापसी",
    contact_support: "सहायता से संपर्क करें",
    usp_1_title: "समय पर किराया पाएँ",
    usp_1_desc: "हर महीने पहली तारीख को किराया जमा।",
    usp_2_title: "शून्य जोखिम",
    usp_2_desc: "किराएदार देरी करे या छोड़ दे, आपको भुगतान मिलेगा।",
    usp_3_title: "आसान मरम्मत और रखरखाव",
    usp_3_desc: "हम शुरू से अंत तक मरम्मत का प्रबंधन करते हैं।",
    usp_4_title: "किराएदार के पीछे न भागें",
    usp_4_desc: "सभी फॉलो-अप और विवाद हम संभालते हैं।",

    // ── Navigation ──────────────────────────────────────────────────────────
    nav_admin_console: "एडमिन कंसोल",
    nav_maintenance: "रखरखाव",
    nav_owner_portal: "मालिक पोर्टल",
    nav_tenant_dashboard: "किराएदार डैशबोर्ड",
    nav_ledger: "खाता बही",
    nav_kyc: "KYC सत्यापन",
    nav_agreement: "समझौता",
    nav_sign_out: "साइन आउट",

    // ── Legal Footer ────────────────────────────────────────────────────────
    footer_refund: "रद्दीकरण/धनवापसी नीति",

    // ── KYC Banner ──────────────────────────────────────────────────────────
    kyc_banner_in_progress: "सत्यापन जारी है",
    kyc_banner_complete: "KYC सत्यापन पूर्ण करें",
    kyc_banner_reviewing: "आपके दस्तावेज़ समीक्षाधीन हैं। इसमें 1-2 कार्यदिवस लग सकते हैं।",
    kyc_banner_verify_owner: "संपत्ति जोड़ने के लिए अपनी पहचान सत्यापित करें।",
    kyc_banner_verify_tenant: "किराया चुकाने के लिए अपनी पहचान सत्यापित करें।",
    kyc_banner_button: "KYC पूर्ण करें",

    // ── Onboarding ──────────────────────────────────────────────────────────
    onboarding_subtitle: "किराया प्रबंधन का भविष्य। हमें बताएं आप कौन हैं।",
    onboarding_iam_landlord: "मैं मकान मालिक हूँ",
    onboarding_landlord_desc: "किराया अग्रिम प्राप्त करें",
    onboarding_iam_tenant: "मैं किराएदार हूँ",
    onboarding_tenant_desc: "लचीली किस्तों में किराया चुकाएं",
    onboarding_role_later: "आप बाद में सेटिंग्स में अपनी भूमिका बदल सकते हैं",

    // ── Setup ───────────────────────────────────────────────────────────────
    setup_landlord_badge: "मालिक सेटअप",
    setup_tenant_badge: "किराएदार सेटअप",
    setup_owner_heading: "अपनी संपत्ति जोड़ें।",
    setup_tenant_heading: "अपना घर खोजें।",
    setup_owner_subtitle: "किराया अग्रिम प्राप्त करने के लिए अपनी संपत्ति विवरण दर्ज करें।",
    setup_tenant_subtitle: "अपने मकान मालिक के ईमेल से खोजें।",
    setup_property_address: "संपत्ति का पता",
    setup_monthly_rent: "मासिक किराया (₹)",
    setup_payout_day: "भुगतान दिन (1–28)",
    setup_tenant_email: "किराएदार ईमेल",
    setup_tenant_email_optional: "वैकल्पिक — किराएदार को आमंत्रित करें",
    setup_submit: "संपत्ति सेट करें",
    setup_skip: "अभी छोड़ें",
    setup_landlord_email: "मकान मालिक का ईमेल",
    setup_available_properties: "उपलब्ध संपत्तियाँ",
    setup_join: "जुड़ें",
    setup_all_set: "आप तैयार हैं!",
    setup_redirecting: "डैशबोर्ड पर जा रहे हैं...",
    setup_month: "माह",
    setup_payout_day_label: "भुगतान दिन",

    // ── Owner Dashboard ─────────────────────────────────────────────────────
    owner_title: "मालिक पोर्टल",
    owner_subtitle: "वापसी पर स्वागत। आपका पोर्टफोलियो अवलोकन।",
    owner_add_property: "नई संपत्ति जोड़ें",
    owner_add_kyc_required: "संपत्ति जोड़ें (KYC आवश्यक)",
    owner_rent_credited: "किराया जमा",
    owner_awaiting_payout: "भुगतान की प्रतीक्षा",
    owner_payout_status: "भुगतान स्थिति",
    owner_credited_on: "आपके बैंक खाते में जमा:",
    owner_active_properties: "सक्रिय संपत्तियाँ",
    owner_recent_activity: "हाल की गतिविधि",
    owner_rent_advanced: "किराया अग्रिम",
    owner_pending_advance: "अग्रिम लंबित",
    owner_no_activity: "हाल की कोई गतिविधि नहीं।",
    owner_due_day: "देय दिन:",
    owner_open: "खुला",
    owner_resolved: "हल किया",
    owner_property_health: "संपत्ति स्वास्थ्य",
    owner_paid_badge: "भुगतान किया",
    owner_pending_badge: "लंबित",
    modal_add_property: "संपत्ति जोड़ें",
    modal_monthly_rent: "मासिक किराया (₹)",
    modal_payout_day: "भुगतान दिन",
    modal_tenant_email_optional: "किराएदार ईमेल (वैकल्पिक)",
    modal_tenant_email_hint: "किराएदार का ईमेल दर्ज करें",
    modal_submit_property: "संपत्ति जोड़ें",

    // ── Tenant Dashboard ────────────────────────────────────────────────────
    tenant_title: "किराएदार डैशबोर्ड",
    tenant_secure_pay: "RentFLO सुरक्षित भुगतान",
    tenant_manage_stay: "यहाँ अपने प्रवास का प्रबंधन करें:",
    tenant_your_residence: "आपका निवास",
    tenant_monthly_rent: "मासिक किराया",
    tenant_settlement_progress: "निपटान प्रगति",
    tenant_settled: "निपटाया",
    tenant_paid: "भुगतान:",
    tenant_remaining: "शेष:",
    tenant_payment_history: "भुगतान इतिहास",
    tenant_payment_heading: "भुगतान",
    tenant_choose_method: "भुगतान विधि चुनें।",
    tenant_flexible: "लचीला",
    tenant_full_only: "पूर्ण केवल",
    tenant_amount_to_pay: "भुगतान राशि (₹)",
    tenant_full_payment_amount: "पूर्ण भुगतान राशि",
    tenant_bank_security: "बैंक-स्तरीय सुरक्षा से संरक्षित",
    tenant_recent_activity: "हाल की गतिविधि",
    tenant_split_payment: "विभाजित भुगतान",
    tenant_payment_pending: "भुगतान लंबित",
    tenant_payment_failed: "भुगतान विफल",
    tenant_maintenance: "रखरखाव",
    tenant_cancel: "रद्द करें",
    tenant_request_fix: "समाधान अनुरोध",
    tenant_issue_title: "समस्या शीर्षक",
    tenant_description: "विवरण",
    tenant_photo_proof: "फोटो प्रमाण (वैकल्पिक)",
    tenant_upload_photo: "फोटो अपलोड करें",
    tenant_photo_attached: "फोटो संलग्न",
    tenant_submit_request: "अनुरोध सबमिट करें",
    tenant_join_home: "मेरा घर खोजें",
    tenant_join_home_subtitle: "मकान मालिक के ईमेल से संपत्ति खोजें।",
    tenant_landlord_email: "मकान मालिक ईमेल",
    tenant_search: "खोज",
    tenant_available_properties: "उपलब्ध संपत्तियाँ",
    tenant_rent_label: "किराया:",
    tenant_per_month: "/माह",
    tenant_join: "जुड़ें",
    tenant_no_active_rent: "कोई सक्रिय किराया नहीं",
    tenant_no_active_rent_desc: "संपत्ति से जुड़ने के बाद किराया यहाँ दिखेगा।",
    tenant_full_prefix: "पूर्ण:",

    // ── Admin Dashboard ─────────────────────────────────────────────────────
    admin_title: "व्यवस्थापक डैशबोर्ड",
    admin_system_status: "सिस्टम स्थिति:",
    admin_operational: "क्रियाशील",
    admin_download_audit: "ऑडिट लॉग डाउनलोड करें",
    admin_tab_overview: "वित्तीय अवलोकन",
    admin_tab_kyc: "KYC अनुमोदन",
    admin_tab_users: "सभी उपयोगकर्ता",
    admin_total_exposure: "कुल एक्सपोज़र",
    admin_advanced: "अग्रिम",
    admin_collected: "संग्रहीत",
    admin_exposure_subtitle: "मालिकों को दिया गया − किराएदारों से लिया गया",
    admin_total_advanced: "कुल अग्रिम",
    admin_total_collected: "कुल संग्रहीत",
    admin_pending_payouts: "लंबित भुगतान",
    admin_active_properties: "सक्रिय संपत्तियाँ",
    admin_capital_deployed: "मालिकों को दी गई पूंजी",
    admin_revenue_recovered: "किराएदारों से वसूली",
    admin_actions_required: "तत्काल कार्रवाई आवश्यक",
    admin_priority_high: "प्राथमिकता: उच्च",
    admin_no_pending_payouts: "कोई लंबित भुगतान नहीं।",
    admin_liquidity_ratio: "तरलता अनुपात",
    admin_liquidity_desc: "तैनात पूंजी और वसूली की तुलना।",
    admin_all_properties: "सभी संपत्तियाँ",
    admin_total_label: "कुल",
    admin_property_address: "संपत्ति का पता",
    admin_monthly_rent: "मासिक किराया",
    admin_owner_id: "मालिक ID",
    admin_occupancy: "अधिभोग",
    admin_occupied: "कब्जा",
    admin_vacant: "रिक्त",
    admin_no_properties: "अभी तक कोई संपत्ति पंजीकृत नहीं।",
    admin_pending_kyc: "लंबित KYC सत्यापन",
    admin_no_kyc: "कोई लंबित KYC नहीं।",
    admin_users_title: "सभी उपयोगकर्ता",
    admin_name: "नाम",
    admin_email: "ईमेल",
    admin_role: "भूमिका",
    admin_kyc_status: "KYC स्थिति",
    admin_verified: "सत्यापित",
    admin_pending: "लंबित",
    admin_not_submitted: "सबमिट नहीं",
    admin_verify_user: "उपयोगकर्ता सत्यापित करें",
    admin_no_role: "कोई भूमिका नहीं",
    admin_mark_paid: "भुगतान की पुष्टि करें",
    admin_net_transfer: "शुद्ध हस्तांतरण",
    admin_platform_fee: "प्लेटफ़ॉर्म शुल्क (5%)",
    admin_confirm_amount: "राशि की पुष्टि करें",
    admin_bank_receipt: "बैंक ट्रांसफर रसीद",
    admin_receipt_hint: "बैंक ट्रांसफर का स्क्रीनशॉट अपलोड करें।",
    admin_stat_properties_sub: "वर्तमान में प्रबंधित पोर्टफोलियो",
    admin_kyc_pan: "PAN",
    admin_kyc_aadhaar: "आधार",
    admin_kyc_bank: "बैंक A/C",
    admin_kyc_ifsc: "IFSC",
    admin_kyc_view_doc: "ID दस्तावेज़ देखें",
    admin_kyc_view_cheque: "रद्द चेक देखें",
    admin_due_now: "अभी देय",
    admin_net_payout: "शुद्ध भुगतान",
    admin_process_payout: "भुगतान संसाधित करें",
    admin_confirm_transfer: "मैनुअल ट्रांसफर की पुष्टि करें",

    // ── Ledger ──────────────────────────────────────────────────────────────
    ledger_title: "मास्टर खाता बही",
    ledger_current_exposure: "वर्तमान एक्सपोज़र",
    ledger_date: "दिनांक",
    ledger_txn_id: "लेनदेन ID",
    ledger_property: "संपत्ति",
    ledger_action: "क्रिया",
    ledger_amount: "राशि",
    ledger_balance: "शेष",
    ledger_no_transactions: "अभी कोई लेनदेन नहीं।",
    ledger_footer: "बैंक-स्तरीय ऑडिट • रियल-टाइम सिंक • संस्थागत पारदर्शिता",
    ledger_balance_label: "शेष:",

    // ── Admin Maintenance ───────────────────────────────────────────────────
    maint_title: "रखरखाव पोर्टल",
    maint_subtitle: "सभी रखरखाव अनुरोध प्रबंधित करें।",
    maint_total: "कुल",
    maint_open: "खुला",
    maint_resolved: "हल किया",
    maint_open_requests: "खुले अनुरोध",
    maint_no_open: "कोई खुले अनुरोध नहीं।",
    maint_no_resolved: "अभी कोई हल नहीं।",
    maint_date: "दिनांक",
    maint_title_col: "शीर्षक",
    maint_property: "संपत्ति",
    maint_resolve: "हल करें",
    maint_view_photo: "फोटो देखें",
    maint_click_close: "बंद करने के लिए कहीं भी क्लिक करें",

    // ── KYC Verify page ─────────────────────────────────────────────────────
    kyc_identity_badge: "पहचान सत्यापन",
    kyc_page_title: "KYC सत्यापन",
    kyc_page_subtitle: "सभी सुविधाएँ अनलॉक करने के लिए पहचान जाँच करें।",
    kyc_verified_title: "KYC सत्यापित",
    kyc_verified_desc: "आपकी पहचान सत्यापित हो गई। अगला चरण: समझौते पर हस्ताक्षर करें।",
    kyc_sign_agreement: "समझौते पर हस्ताक्षर करें",
    kyc_under_review_title: "समीक्षाधीन",
    kyc_under_review_desc: "आपके दस्तावेज़ समीक्षाधीन हैं। 1–2 कार्यदिवस लग सकते हैं।",
    kyc_identity_info: "पहचान जानकारी",
    kyc_full_legal_name: "पूरा कानूनी नाम",
    kyc_name_placeholder: "जैसा आपके दस्तावेज़ पर है",
    kyc_id_type: "ID प्रकार",
    kyc_choose_one: "(एक चुनें)",
    kyc_pan_card: "पैन कार्ड",
    kyc_aadhaar: "आधार",
    kyc_pan_number: "पैन नंबर",
    kyc_pan_hint: "10-अक्षर अल्फान्यूमेरिक",
    kyc_aadhaar_number: "आधार नंबर",
    kyc_aadhaar_hint: "12 अंकों का आधार नंबर",
    kyc_upload_pan: "पैन कार्ड अपलोड करें",
    kyc_upload_aadhaar: "आधार कार्ड अपलोड करें",
    kyc_doc_uploaded: "दस्तावेज़ अपलोड ✓",
    kyc_choose_file: "फाइल चुनें (छवि या PDF)",
    kyc_doc_ready: "दस्तावेज़ अपलोड के लिए तैयार।",
    kyc_bank_details: "बैंक विवरण",
    kyc_landlords_only: "(केवल मकान मालिक)",
    kyc_account_number: "खाता संख्या",
    kyc_account_placeholder: "खाता नंबर दर्ज करें",
    kyc_ifsc_code: "IFSC कोड",
    kyc_cancelled_cheque: "रद्द चेक",
    kyc_uploaded_tick: "अपलोड ✓",
    kyc_upload_cheque: "चेक अपलोड करें",
    kyc_submitting: "सबमिट हो रहा है…",
    kyc_submit: "सत्यापन के लिए सबमिट करें",

    // ── Agreement page ──────────────────────────────────────────────────────
    agr_badge: "त्रिपक्षीय समझौता",
    agr_title: "अपने समझौते पर हस्ताक्षर करें",
    agr_subtitle: "नीचे पूरा समझौता पढ़ें, फिर डिजिटल हस्ताक्षर करें।",
    agr_no_property: "कोई संपत्ति नहीं मिली। पहले संपत्ति सेटअप पूरा करें।",
    agr_go_to_setup: "सेटअप पर जाएं",
    agr_signed_title: "समझौता हस्ताक्षरित",
    agr_signed_desc: "आपका डिजिटल हस्ताक्षर RentFLO लेजर में दर्ज हो गया।",
    agr_both_signed: " दोनों पक्षों ने हस्ताक्षर किए — समझौता पूरी तरह निष्पादित।",
    agr_waiting_other: " दूसरे पक्ष के हस्ताक्षर की प्रतीक्षा है।",
    agr_go_to_dashboard: "डैशबोर्ड पर जाएं",
    agr_scroll_hint: "↓ हस्ताक्षर से पहले पूरा समझौता पढ़ें",
    agr_your_signature: "आपका डिजिटल हस्ताक्षर",
    agr_read_to_unlock: "हस्ताक्षर पैड अनलॉक करने के लिए ऊपर पूरा समझौता पढ़ें।",
    agr_recording: "आपका हस्ताक्षर दर्ज हो रहा है…",
    agr_draw_here: "यहाँ हस्ताक्षर करें",
    agr_clear: "साफ करें",
    agr_confirm_signature: "हस्ताक्षर पुष्टि करें",
    agr_rentflo_party: "RentFLO",
    agr_landlord_party: "मालिक",
    agr_tenant_party: "किराएदार",
    agr_signed_tick: "✓ हस्ताक्षरित",
    agr_pending: "लंबित",
    agr_rent_advance: "किराया अग्रिम समझौता",
  },

  kn: {
    // ── Landing page ────────────────────────────────────────────────────────
    home: "ಮುಖಪುಟ",
    settings: "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
    welcome_message: "RentFLO ಗೆ ಸ್ವಾಗತ",
    login: "ಲಾಗಿನ್",
    change_language: "ಭಾಷೆ ಬದಲಾಯಿಸಿ",
    dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    tenant: "ಬಾಡಿಗೆದಾರ",
    owner: "ಮಾಲೀಕ",
    admin: "ನಿರ್ವಾಹಕ",
    properties: "ಆಸ್ತಿಗಳು",
    payments: "ಪಾವತಿಗಳು",
    support: "ಬೆಂಬಲ",
    logout: "ಲಾಗ್ಔಟ್",
    never_chase_rent: "ಬಾಡಿಗೆ ಹಿಂದೆ ಓಡಬೇಡಿ.",
    we_pay_your_rent: "ನಾವು 1ನೇ ತಾರೀಖು ನಿಮ್ಮ ಬಾಡಿಗೆ ಪಾವತಿಸುತ್ತೇವೆ.",
    your_tenant_pays_later: "ನಿಮ್ಮ ಬಾಡಿಗೆದಾರರು ನಂತರ ನಮಗೆ ಪಾವತಿಸುತ್ತಾರೆ.",
    zero_friction: "ಯಾವುದೇ ತೊಂದರೆಯಿಲ್ಲ.",
    get_started: "ಪ್ರಾರಂಭಿಸಿ",
    view_demo: "ಡೆಮೊ ನೋಡಿ",
    terms: "ಸೇವಾ ನಿಯಮಗಳು",
    privacy: "ಗೌಪ್ಯತಾ ನೀತಿ",
    refund: "ರದ್ದು ಮತ್ತು ಮರುಪಾವತಿ",
    contact_support: "ಬೆಂಬಲವನ್ನು ಸಂಪರ್ಕಿಸಿ",
    usp_1_title: "ಸಮಯಕ್ಕೆ ಸರಿಯಾಗಿ ಬಾಡಿಗೆ ಪಡೆಯಿರಿ",
    usp_1_desc: "ಪ್ರತಿ ತಿಂಗಳ 1ನೇ ತಾರೀಖು ಬಾಡಿಗೆ ಜಮಾ.",
    usp_2_title: "ಶೂನ್ಯ ಅಪಾಯ",
    usp_2_desc: "ಬಾಡಿಗೆದಾರರು ವಿಳಂಬಿಸಿದರೂ ಅಥವಾ ಬಿಟ್ಟರೂ ನಿಮಗೆ ಪಾವತಿ ಸಿಗುತ್ತದೆ.",
    usp_3_title: "ಸುಲಭ ದುರಸ್ತಿ ಮತ್ತು ನಿರ್ವಹಣೆ",
    usp_3_desc: "ನಾವು ಆರಂಭದಿಂದ ಕೊನೆಯವರೆಗೆ ದುರಸ್ತಿ ನಿರ್ವಹಿಸುತ್ತೇವೆ.",
    usp_4_title: "ಬಾಡಿಗೆದಾರರ ಹಿಂದೆ ಓಡಬೇಡಿ",
    usp_4_desc: "ಎಲ್ಲಾ ಫಾಲೋ-ಅಪ್ ಮತ್ತು ವಿವಾದಗಳನ್ನು ನಾವು ನಿಭಾಯಿಸುತ್ತೇವೆ.",

    // ── Navigation ──────────────────────────────────────────────────────────
    nav_admin_console: "ಅಡ್ಮಿನ್ ಕನ್ಸೋಲ್",
    nav_maintenance: "ನಿರ್ವಹಣೆ",
    nav_owner_portal: "ಮಾಲೀಕ ಪೋರ್ಟಲ್",
    nav_tenant_dashboard: "ಬಾಡಿಗೆದಾರ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    nav_ledger: "ಲೆಡ್ಜರ್",
    nav_kyc: "KYC ಪರಿಶೀಲನೆ",
    nav_agreement: "ಒಪ್ಪಂದ",
    nav_sign_out: "ಸೈನ್ ಔಟ್",

    // ── Legal Footer ────────────────────────────────────────────────────────
    footer_refund: "ರದ್ದು/ಮರುಪಾವತಿ ನೀತಿ",

    // ── KYC Banner ──────────────────────────────────────────────────────────
    kyc_banner_in_progress: "ಪರಿಶೀಲನೆ ಪ್ರಗತಿಯಲ್ಲಿದೆ",
    kyc_banner_complete: "KYC ಪರಿಶೀಲನೆ ಪೂರ್ಣಗೊಳಿಸಿ",
    kyc_banner_reviewing: "ನಿಮ್ಮ ದಾಖಲೆಗಳನ್ನು ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ. ಇದು ಸಾಮಾನ್ಯವಾಗಿ 1-2 ವ್ಯಾಪಾರ ದಿನ ತೆಗೆದುಕೊಳ್ಳುತ್ತದೆ.",
    kyc_banner_verify_owner: "ಆಸ್ತಿ ಸೇರಿಸಲು ನಿಮ್ಮ ಗುರುತು ಪರಿಶೀಲಿಸಿ.",
    kyc_banner_verify_tenant: "ಬಾಡಿಗೆ ಪಾವತಿ ಮಾಡಲು ನಿಮ್ಮ ಗುರುತು ಪರಿಶೀಲಿಸಿ.",
    kyc_banner_button: "KYC ಪೂರ್ಣಗೊಳಿಸಿ",

    // ── Onboarding ──────────────────────────────────────────────────────────
    onboarding_subtitle: "ಬಾಡಿಗೆ ನಿರ್ವಹಣೆಯ ಭವಿಷ್ಯ. ನೀವು ಯಾರು ಎಂದು ನಮಗೆ ತಿಳಿಸಿ.",
    onboarding_iam_landlord: "ನಾನು ಮನೆಮಾಲೀಕ",
    onboarding_landlord_desc: "ಮುಂಗಡ ಬಾಡಿಗೆ ಪಡೆಯಿರಿ",
    onboarding_iam_tenant: "ನಾನು ಬಾಡಿಗೆದಾರ",
    onboarding_tenant_desc: "ಹಂತಹಂತವಾಗಿ ಬಾಡಿಗೆ ಪಾವತಿಸಿ",
    onboarding_role_later: "ನೀವು ನಂತರ ಸೆಟ್ಟಿಂಗ್‌ಗಳಲ್ಲಿ ನಿಮ್ಮ ಪಾತ್ರ ಬದಲಾಯಿಸಬಹುದು",

    // ── Setup ───────────────────────────────────────────────────────────────
    setup_landlord_badge: "ಮಾಲೀಕ ಸೆಟಪ್",
    setup_tenant_badge: "ಬಾಡಿಗೆದಾರ ಸೆಟಪ್",
    setup_owner_heading: "ನಿಮ್ಮ ಆಸ್ತಿ ಸೇರಿಸಿ.",
    setup_tenant_heading: "ನಿಮ್ಮ ಮನೆ ಹುಡುಕಿ.",
    setup_owner_subtitle: "ಬಾಡಿಗೆ ಮುಂಗಡ ಪಡೆಯಲು ಆಸ್ತಿ ವಿವರ ನಮೂದಿಸಿ.",
    setup_tenant_subtitle: "ನಿಮ್ಮ ಮನೆಮಾಲೀಕರ ಇಮೇಲ್‌ನಿಂದ ಹುಡುಕಿ.",
    setup_property_address: "ಆಸ್ತಿ ವಿಳಾಸ",
    setup_monthly_rent: "ಮಾಸಿಕ ಬಾಡಿಗೆ (₹)",
    setup_payout_day: "ಪಾವತಿ ದಿನ (1–28)",
    setup_tenant_email: "ಬಾಡಿಗೆದಾರ ಇಮೇಲ್",
    setup_tenant_email_optional: "ಐಚ್ಛಿಕ — ಬಾಡಿಗೆದಾರರನ್ನು ಆಮಂತ್ರಿಸಿ",
    setup_submit: "ಆಸ್ತಿ ಹೊಂದಿಸಿ",
    setup_skip: "ಈಗ ಬಿಟ್ಟುಬಿಡಿ",
    setup_landlord_email: "ಮನೆಮಾಲೀಕ ಇಮೇಲ್",
    setup_available_properties: "ಲಭ್ಯ ಆಸ್ತಿಗಳು",
    setup_join: "ಸೇರಿ",
    setup_all_set: "ನೀವು ಸಿದ್ಧರಾಗಿದ್ದೀರಿ!",
    setup_redirecting: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ಮರುನಿರ್ದೇಶಿಸಲಾಗುತ್ತಿದೆ…",
    setup_month: "ತಿಂಗಳು",
    setup_payout_day_label: "ಪಾವತಿ ದಿನ",

    // ── Owner Dashboard ─────────────────────────────────────────────────────
    owner_title: "ಮಾಲೀಕ ಪೋರ್ಟಲ್",
    owner_subtitle: "ಮರಳಿ ಸ್ವಾಗತ. ನಿಮ್ಮ ಪೋರ್ಟ್‌ಫೋಲಿಯೊ ಅವಲೋಕನ.",
    owner_add_property: "ಹೊಸ ಆಸ್ತಿ ಸೇರಿಸಿ",
    owner_add_kyc_required: "ಆಸ್ತಿ ಸೇರಿಸಿ (KYC ಅಗತ್ಯ)",
    owner_rent_credited: "ಬಾಡಿಗೆ ಜಮೆ",
    owner_awaiting_payout: "ಪಾವತಿ ನಿರೀಕ್ಷಿಸಲಾಗುತ್ತಿದೆ",
    owner_payout_status: "ಪಾವತಿ ಸ್ಥಿತಿ",
    owner_credited_on: "ನಿಮ್ಮ ಬ್ಯಾಂಕ್ ಖಾತೆಗೆ ಜಮೆ:",
    owner_active_properties: "ಸಕ್ರಿಯ ಆಸ್ತಿಗಳು",
    owner_recent_activity: "ಇತ್ತೀಚಿನ ಚಟುವಟಿಕೆ",
    owner_rent_advanced: "ಬಾಡಿಗೆ ಮುಂಗಡ",
    owner_pending_advance: "ಮುಂಗಡ ಬಾಕಿ",
    owner_no_activity: "ಇತ್ತೀಚಿನ ಚಟುವಟಿಕೆ ಇಲ್ಲ.",
    owner_due_day: "ಗಡುವು ದಿನ:",
    owner_open: "ತೆರೆದ",
    owner_resolved: "ಪರಿಹರಿಸಲಾಗಿದೆ",
    owner_property_health: "ಆಸ್ತಿ ಆರೋಗ್ಯ",
    owner_paid_badge: "ಪಾವತಿ ಮಾಡಲಾಗಿದೆ",
    owner_pending_badge: "ಬಾಕಿ",
    modal_add_property: "ಆಸ್ತಿ ಸೇರಿಸಿ",
    modal_monthly_rent: "ಮಾಸಿಕ ಬಾಡಿಗೆ (₹)",
    modal_payout_day: "ಪಾವತಿ ದಿನ",
    modal_tenant_email_optional: "ಬಾಡಿಗೆದಾರ ಇಮೇಲ್ (ಐಚ್ಛಿಕ)",
    modal_tenant_email_hint: "ಬಾಡಿಗೆದಾರ ಇಮೇಲ್ ನಮೂದಿಸಿ",
    modal_submit_property: "ಆಸ್ತಿ ಸೇರಿಸಿ",

    // ── Tenant Dashboard ────────────────────────────────────────────────────
    tenant_title: "ಬಾಡಿಗೆದಾರ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    tenant_secure_pay: "RentFLO ಸುರಕ್ಷಿತ ಪಾವತಿ",
    tenant_manage_stay: "ಇಲ್ಲಿ ನಿಮ್ಮ ವಾಸ್ತವ್ಯ ನಿರ್ವಹಿಸಿ:",
    tenant_your_residence: "ನಿಮ್ಮ ನಿವಾಸ",
    tenant_monthly_rent: "ಮಾಸಿಕ ಬಾಡಿಗೆ",
    tenant_settlement_progress: "ಇತ್ಯರ್ಥ ಪ್ರಗತಿ",
    tenant_settled: "ಇತ್ಯರ್ಥ",
    tenant_paid: "ಪಾವತಿ:",
    tenant_remaining: "ಉಳಿದಿರುವ:",
    tenant_payment_history: "ಪಾವತಿ ಇತಿಹಾಸ",
    tenant_payment_heading: "ಪಾವತಿ",
    tenant_choose_method: "ಪಾವತಿ ವಿಧಾನ ಆಯ್ಕೆ ಮಾಡಿ.",
    tenant_flexible: "ಹೊಂದಿಕೊಳ್ಳಬಲ್ಲ",
    tenant_full_only: "ಪೂರ್ಣ ಮಾತ್ರ",
    tenant_amount_to_pay: "ಪಾವತಿ ಮೊತ್ತ (₹)",
    tenant_full_payment_amount: "ಪೂರ್ಣ ಪಾವತಿ ಮೊತ್ತ",
    tenant_bank_security: "ಬ್ಯಾಂಕ್ ದರ್ಜೆಯ ಸುರಕ್ಷತೆಯಿಂದ ರಕ್ಷಿಸಲ್ಪಟ್ಟಿದೆ",
    tenant_recent_activity: "ಇತ್ತೀಚಿನ ಚಟುವಟಿಕೆ",
    tenant_split_payment: "ವಿಭಜಿತ ಪಾವತಿ",
    tenant_payment_pending: "ಪಾವತಿ ಬಾಕಿ",
    tenant_payment_failed: "ಪಾವತಿ ವಿಫಲ",
    tenant_maintenance: "ನಿರ್ವಹಣೆ",
    tenant_cancel: "ರದ್ದು",
    tenant_request_fix: "ಸರಿಪಡಿಸಲು ಕೋರಿ",
    tenant_issue_title: "ಸಮಸ್ಯೆ ಶೀರ್ಷಿಕೆ",
    tenant_description: "ವಿವರಣೆ",
    tenant_photo_proof: "ಫೋಟೋ ಪ್ರಮಾಣ (ಐಚ್ಛಿಕ)",
    tenant_upload_photo: "ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    tenant_photo_attached: "ಫೋಟೋ ಲಗತ್ತಿಸಲಾಗಿದೆ",
    tenant_submit_request: "ವಿನಂತಿ ಸಲ್ಲಿಸಿ",
    tenant_join_home: "ನನ್ನ ಮನೆ ಸೇರಿ",
    tenant_join_home_subtitle: "ಮನೆಮಾಲೀಕರ ಇಮೇಲ್‌ನಿಂದ ಆಸ್ತಿ ಹುಡುಕಿ.",
    tenant_landlord_email: "ಮನೆಮಾಲೀಕ ಇಮೇಲ್",
    tenant_search: "ಹುಡುಕು",
    tenant_available_properties: "ಲಭ್ಯ ಆಸ್ತಿಗಳು",
    tenant_rent_label: "ಬಾಡಿಗೆ:",
    tenant_per_month: "/ತಿಂಗಳು",
    tenant_join: "ಸೇರಿ",
    tenant_no_active_rent: "ಸಕ್ರಿಯ ಬಾಡಿಗೆ ಇಲ್ಲ",
    tenant_no_active_rent_desc: "ಆಸ್ತಿ ಸೇರಿದ ನಂತರ, ಬಾಡಿಗೆ ಪಾವತಿ ಇಲ್ಲಿ ಕಾಣಿಸುತ್ತದೆ.",
    tenant_full_prefix: "ಪೂರ್ಣ:",

    // ── Admin Dashboard ─────────────────────────────────────────────────────
    admin_title: "ಅಡ್ಮಿನ್ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    admin_system_status: "ಸಿಸ್ಟಮ್ ಸ್ಥಿತಿ:",
    admin_operational: "ಕಾರ್ಯಾಚರಣೆ",
    admin_download_audit: "ಆಡಿಟ್ ಲಾಗ್ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ",
    admin_tab_overview: "ಹಣಕಾಸು ಅವಲೋಕನ",
    admin_tab_kyc: "KYC ಅನುಮೋದನೆ",
    admin_tab_users: "ಎಲ್ಲಾ ಬಳಕೆದಾರರು",
    admin_total_exposure: "ಒಟ್ಟು ಎಕ್ಸ್‌ಪೋಶರ್",
    admin_advanced: "ಮುಂಗಡ",
    admin_collected: "ಸಂಗ್ರಹಿಸಲಾಗಿದೆ",
    admin_exposure_subtitle: "ಮಾಲೀಕರಿಗೆ ನೀಡಲಾಗಿದೆ − ಬಾಡಿಗೆದಾರರಿಂದ ಸಂಗ್ರಹಿಸಲಾಗಿದೆ",
    admin_total_advanced: "ಒಟ್ಟು ಮುಂಗಡ",
    admin_total_collected: "ಒಟ್ಟು ಸಂಗ್ರಹ",
    admin_pending_payouts: "ಬಾಕಿ ಪಾವತಿ",
    admin_active_properties: "ಸಕ್ರಿಯ ಆಸ್ತಿಗಳು",
    admin_capital_deployed: "ಮಾಲೀಕರಿಗೆ ನಿಯೋಜಿಸಲಾದ ಬಂಡವಾಳ",
    admin_revenue_recovered: "ಬಾಡಿಗೆದಾರರಿಂದ ವಸೂಲಿ",
    admin_actions_required: "ತಕ್ಷಣ ಕ್ರಮ ಅಗತ್ಯ",
    admin_priority_high: "ಆದ್ಯತೆ: ಹೆಚ್ಚು",
    admin_no_pending_payouts: "ಯಾವುದೇ ಬಾಕಿ ಪಾವತಿ ಇಲ್ಲ.",
    admin_liquidity_ratio: "ತರಲತೆ ಅನುಪಾತ",
    admin_liquidity_desc: "ನಿಯೋಜಿತ ಬಂಡವಾಳ ಮತ್ತು ಸಂಗ್ರಹಿಸಿದ ಆದಾಯದ ತುಲನೆ.",
    admin_all_properties: "ಎಲ್ಲಾ ಆಸ್ತಿಗಳು",
    admin_total_label: "ಒಟ್ಟು",
    admin_property_address: "ಆಸ್ತಿ ವಿಳಾಸ",
    admin_monthly_rent: "ಮಾಸಿಕ ಬಾಡಿಗೆ",
    admin_owner_id: "ಮಾಲೀಕ ID",
    admin_occupancy: "ಆಕ್ರಮಣ",
    admin_occupied: "ಆಕ್ರಮಿಸಲಾಗಿದೆ",
    admin_vacant: "ಖಾಲಿ",
    admin_no_properties: "ಇನ್ನೂ ಯಾವುದೇ ಆಸ್ತಿ ನೋಂದಾಯಿಸಲಾಗಿಲ್ಲ.",
    admin_pending_kyc: "ಬಾಕಿ KYC ಪರಿಶೀಲನೆ",
    admin_no_kyc: "ಯಾವುದೇ ಬಾಕಿ KYC ಇಲ್ಲ.",
    admin_users_title: "ಎಲ್ಲಾ ಬಳಕೆದಾರರು",
    admin_name: "ಹೆಸರು",
    admin_email: "ಇಮೇಲ್",
    admin_role: "ಪಾತ್ರ",
    admin_kyc_status: "KYC ಸ್ಥಿತಿ",
    admin_verified: "ಪರಿಶೀಲಿಸಲಾಗಿದೆ",
    admin_pending: "ಬಾಕಿ",
    admin_not_submitted: "ಸಲ್ಲಿಸಲಾಗಿಲ್ಲ",
    admin_verify_user: "ಬಳಕೆದಾರ ಪರಿಶೀಲಿಸಿ",
    admin_no_role: "ಪಾತ್ರ ಇಲ್ಲ",
    admin_mark_paid: "ಪಾವತಿ ದೃಢೀಕರಿಸಿ",
    admin_net_transfer: "ನಿವ್ವಳ ವರ್ಗಾವಣೆ",
    admin_platform_fee: "ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ಶುಲ್ಕ (5%)",
    admin_confirm_amount: "ಮೊತ್ತ ದೃಢೀಕರಿಸಿ",
    admin_bank_receipt: "ಬ್ಯಾಂಕ್ ವರ್ಗಾವಣೆ ರಶೀದಿ",
    admin_receipt_hint: "ಬ್ಯಾಂಕ್ ವರ್ಗಾವಣೆ ಸ್ಕ್ರೀನ್‌ಶಾಟ್ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.",
    admin_stat_properties_sub: "ಪ್ರಸ್ತುತ ನಿರ್ವಹಿಸಲಾಗುತ್ತಿರುವ ಪೋರ್ಟ್‌ಫೋಲಿಯೊ",
    admin_kyc_pan: "PAN",
    admin_kyc_aadhaar: "ಆಧಾರ್",
    admin_kyc_bank: "ಬ್ಯಾಂಕ್ A/C",
    admin_kyc_ifsc: "IFSC",
    admin_kyc_view_doc: "ID ದಾಖಲೆ ನೋಡಿ",
    admin_kyc_view_cheque: "ರದ್ದಾದ ಚೆಕ್ ನೋಡಿ",
    admin_due_now: "ಈಗ ಬಾಕಿ",
    admin_net_payout: "ನಿವ್ವಳ ಪಾವತಿ",
    admin_process_payout: "ಪಾವತಿ ಸಂಸ್ಕರಿಸಿ",
    admin_confirm_transfer: "ಕೈಪಿಡಿ ವರ್ಗಾವಣೆ ದೃಢೀಕರಿಸಿ",

    // ── Ledger ──────────────────────────────────────────────────────────────
    ledger_title: "ಮಾಸ್ಟರ್ ಲೆಡ್ಜರ್",
    ledger_current_exposure: "ಪ್ರಸ್ತುತ ಎಕ್ಸ್‌ಪೋಶರ್",
    ledger_date: "ದಿನಾಂಕ",
    ledger_txn_id: "ವಹಿವಾಟು ID",
    ledger_property: "ಆಸ್ತಿ",
    ledger_action: "ಕ್ರಿಯೆ",
    ledger_amount: "ಮೊತ್ತ",
    ledger_balance: "ಬ್ಯಾಲೆನ್ಸ್",
    ledger_no_transactions: "ಇನ್ನೂ ಯಾವುದೇ ವಹಿವಾಟು ಇಲ್ಲ.",
    ledger_footer: "ಬ್ಯಾಂಕ್ ದರ್ಜೆ ಆಡಿಟ್ • ರಿಯಲ್-ಟೈಮ್ ಸಿಂಕ್ • ಸಾಂಸ್ಥಿಕ ಪಾರದರ್ಶಿತೆ",
    ledger_balance_label: "ಬ್ಯಾಲೆನ್ಸ್:",

    // ── Admin Maintenance ───────────────────────────────────────────────────
    maint_title: "ನಿರ್ವಹಣೆ ಪೋರ್ಟಲ್",
    maint_subtitle: "ಎಲ್ಲಾ ಆಸ್ತಿ ನಿರ್ವಹಣೆ ವಿನಂತಿಗಳನ್ನು ನಿರ್ವಹಿಸಿ.",
    maint_total: "ಒಟ್ಟು",
    maint_open: "ತೆರೆದ",
    maint_resolved: "ಪರಿಹರಿಸಲಾಗಿದೆ",
    maint_open_requests: "ತೆರೆದ ವಿನಂತಿಗಳು",
    maint_no_open: "ಯಾವುದೇ ತೆರೆದ ನಿರ್ವಹಣೆ ವಿನಂತಿ ಇಲ್ಲ.",
    maint_no_resolved: "ಇನ್ನೂ ಯಾವುದೇ ಪರಿಹರಿಸಲಾದ ಟಿಕೆಟ್ ಇಲ್ಲ.",
    maint_date: "ದಿನಾಂಕ",
    maint_title_col: "ಶೀರ್ಷಿಕೆ",
    maint_property: "ಆಸ್ತಿ",
    maint_resolve: "ಪರಿಹರಿಸಿ",
    maint_view_photo: "ಫೋಟೋ ನೋಡಿ",
    maint_click_close: "ಮುಚ್ಚಲು ಎಲ್ಲಿಯಾದರೂ ಕ್ಲಿಕ್ ಮಾಡಿ",

    // ── KYC Verify page ─────────────────────────────────────────────────────
    kyc_identity_badge: "ಗುರುತು ಪರಿಶೀಲನೆ",
    kyc_page_title: "KYC ಪರಿಶೀಲನೆ",
    kyc_page_subtitle: "ಎಲ್ಲಾ ವೈಶಿಷ್ಟ್ಯಗಳನ್ನು ಅನ್‌ಲಾಕ್ ಮಾಡಲು ನಿಮ್ಮ ಗುರುತು ಪರಿಶೀಲಿಸಿ.",
    kyc_verified_title: "KYC ಪರಿಶೀಲಿಸಲಾಗಿದೆ",
    kyc_verified_desc: "ನಿಮ್ಮ ಗುರುತು ಪರಿಶೀಲಿಸಲಾಗಿದೆ. ಮುಂದಿನ ಹಂತ: ನಿಮ್ಮ ಒಪ್ಪಂದಕ್ಕೆ ಸಹಿ ಹಾಕಿ.",
    kyc_sign_agreement: "ನಿಮ್ಮ ಒಪ್ಪಂದಕ್ಕೆ ಸಹಿ ಹಾಕಿ",
    kyc_under_review_title: "ಪರಿಶೀಲನೆಯಲ್ಲಿ",
    kyc_under_review_desc: "ನಿಮ್ಮ ದಾಖಲೆಗಳನ್ನು ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ. ಇದು ಸಾಮಾನ್ಯವಾಗಿ 1–2 ವ್ಯಾಪಾರ ದಿನ ತೆಗೆದುಕೊಳ್ಳುತ್ತದೆ.",
    kyc_identity_info: "ಗುರುತು ಮಾಹಿತಿ",
    kyc_full_legal_name: "ಪೂರ್ಣ ಕಾನೂನು ಹೆಸರು",
    kyc_name_placeholder: "ನಿಮ್ಮ ಗುರುತು ದಾಖಲೆಯಲ್ಲಿ ಇರುವಂತೆ",
    kyc_id_type: "ID ಪ್ರಕಾರ",
    kyc_choose_one: "(ಒಂದು ಆಯ್ಕೆ ಮಾಡಿ)",
    kyc_pan_card: "PAN ಕಾರ್ಡ್",
    kyc_aadhaar: "ಆಧಾರ್",
    kyc_pan_number: "PAN ಸಂಖ್ಯೆ",
    kyc_pan_hint: "10-ಅಕ್ಷರ ಅಲ್ಫಾನ್ಯೂಮೆರಿಕ್",
    kyc_aadhaar_number: "ಆಧಾರ್ ಸಂಖ್ಯೆ",
    kyc_aadhaar_hint: "12-ಅಂಕಿ ಆಧಾರ್ ಸಂಖ್ಯೆ",
    kyc_upload_pan: "PAN ಕಾರ್ಡ್ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    kyc_upload_aadhaar: "ಆಧಾರ್ ಕಾರ್ಡ್ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    kyc_doc_uploaded: "ದಾಖಲೆ ಅಪ್‌ಲೋಡ್ ✓",
    kyc_choose_file: "ಫೈಲ್ ಆಯ್ಕೆ ಮಾಡಿ (ಚಿತ್ರ ಅಥವಾ PDF)",
    kyc_doc_ready: "ದಾಖಲೆ ಅಪ್‌ಲೋಡ್‌ಗೆ ಸಿದ್ಧ.",
    kyc_bank_details: "ಬ್ಯಾಂಕ್ ವಿವರ",
    kyc_landlords_only: "(ಮನೆಮಾಲೀಕರು ಮಾತ್ರ)",
    kyc_account_number: "ಖಾತೆ ಸಂಖ್ಯೆ",
    kyc_account_placeholder: "ಖಾತೆ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ",
    kyc_ifsc_code: "IFSC ಕೋಡ್",
    kyc_cancelled_cheque: "ರದ್ದಾದ ಚೆಕ್",
    kyc_uploaded_tick: "ಅಪ್‌ಲೋಡ್ ✓",
    kyc_upload_cheque: "ಚೆಕ್ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    kyc_submitting: "ಸಲ್ಲಿಸಲಾಗುತ್ತಿದೆ…",
    kyc_submit: "ಪರಿಶೀಲನೆಗಾಗಿ ಸಲ್ಲಿಸಿ",

    // ── Agreement page ──────────────────────────────────────────────────────
    agr_badge: "ತ್ರಿಪಕ್ಷ ಒಪ್ಪಂದ",
    agr_title: "ನಿಮ್ಮ ಒಪ್ಪಂದಕ್ಕೆ ಸಹಿ ಹಾಕಿ",
    agr_subtitle: "ಕೆಳಗಿನ ಒಪ್ಪಂದ ಓದಿ, ನಂತರ ಡಿಜಿಟಲ್ ಸಹಿ ಮಾಡಿ.",
    agr_no_property: "ಯಾವುದೇ ಆಸ್ತಿ ಕಂಡುಬಂದಿಲ್ಲ. ಮೊದಲು ಸೆಟಪ್ ಪೂರ್ಣಗೊಳಿಸಿ.",
    agr_go_to_setup: "ಸೆಟಪ್‌ಗೆ ಹೋಗಿ",
    agr_signed_title: "ಒಪ್ಪಂದ ಸಹಿ ಮಾಡಲಾಗಿದೆ",
    agr_signed_desc: "ನಿಮ್ಮ ಡಿಜಿಟಲ್ ಸಹಿ RentFLO ಲೆಡ್ಜರ್‌ನಲ್ಲಿ ದಾಖಲಾಗಿದೆ.",
    agr_both_signed: " ಎರಡೂ ಪಕ್ಷಗಳು ಸಹಿ ಮಾಡಿದ್ದಾರೆ — ಒಪ್ಪಂದ ಸಂಪೂರ್ಣ.",
    agr_waiting_other: " ಇನ್ನೊಂದು ಪಕ್ಷದ ಸಹಿಗಾಗಿ ನಿರೀಕ್ಷಿಸಲಾಗುತ್ತಿದೆ.",
    agr_go_to_dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ಹೋಗಿ",
    agr_scroll_hint: "↓ ಸಹಿ ಮಾಡುವ ಮೊದಲು ಪೂರ್ಣ ಒಪ್ಪಂದ ಓದಿ",
    agr_your_signature: "ನಿಮ್ಮ ಡಿಜಿಟಲ್ ಸಹಿ",
    agr_read_to_unlock: "ಸಹಿ ಪ್ಯಾಡ್ ಅನ್‌ಲಾಕ್ ಮಾಡಲು ಮೇಲಿನ ಒಪ್ಪಂದ ಓದಿ.",
    agr_recording: "ನಿಮ್ಮ ಸಹಿ ದಾಖಲಿಸಲಾಗುತ್ತಿದೆ…",
    agr_draw_here: "ಇಲ್ಲಿ ಸಹಿ ಮಾಡಿ",
    agr_clear: "ತೆಳೆಯಿರಿ",
    agr_confirm_signature: "ಸಹಿ ದೃಢೀಕರಿಸಿ",
    agr_rentflo_party: "RentFLO",
    agr_landlord_party: "ಮಾಲೀಕ",
    agr_tenant_party: "ಬಾಡಿಗೆದಾರ",
    agr_signed_tick: "✓ ಸಹಿ",
    agr_pending: "ಬಾಕಿ",
    agr_rent_advance: "ಬಾಡಿಗೆ ಮುಂಗಡ ಒಪ್ಪಂದ",
  },
} as const;

type Language = 'en' | 'hi' | 'kn';
export type TranslationKey = keyof typeof translations.en;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  t: (key) => key,
});

const STORAGE_KEY = 'rentflo_language';

function getSavedLanguage(): Language {
  try {
    const saved = localStorage.getItem(STORAGE_KEY);
    if (saved && ['en', 'hi', 'kn'].includes(saved)) return saved as Language;
  } catch {}
  return 'en';
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLang] = useState<Language>(getSavedLanguage);

  const setLanguage = useCallback((lang: Language) => {
    localStorage.setItem(STORAGE_KEY, lang);
    setLang(lang);
    document.documentElement.lang = lang;
    const select = document.getElementById('language-select') as HTMLSelectElement | null;
    if (select) select.value = lang;
  }, []);

  // Listen for changes coming from the vanilla-JS header selector
  useEffect(() => {
    const handler = (e: Event) => {
      const lang = (e as CustomEvent<{ lang: Language }>).detail?.lang;
      if (lang && ['en', 'hi', 'kn'].includes(lang)) {
        setLang(lang);
        localStorage.setItem(STORAGE_KEY, lang);
        document.documentElement.lang = lang;
      }
    };
    window.addEventListener('languageChange', handler);
    return () => window.removeEventListener('languageChange', handler);
  }, []);

  // Sync html lang attr on mount
  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  const t = useCallback((key: TranslationKey): string => {
    return (translations[language] as Record<string, string>)[key]
      ?? (translations.en as Record<string, string>)[key]
      ?? key;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useI18n() {
  return useContext(LanguageContext);
}

export type { Language };
export { translations };
