// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/rentflo-concepts/GlassDashboard.tsx": () => import("../components/mockups/rentflo-concepts/GlassDashboard.tsx"),
  "./components/mockups/rentflo-concepts/HeroLanding.tsx": () => import("../components/mockups/rentflo-concepts/HeroLanding.tsx"),
  "./components/mockups/rentflo-concepts/PaymentReceipt.tsx": () => import("../components/mockups/rentflo-concepts/PaymentReceipt.tsx"),
  "./components/mockups/rentflo-concepts/TiltCards.tsx": () => import("../components/mockups/rentflo-concepts/TiltCards.tsx")
};
