// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/tenant-dashboard-variants/BoldNeon.tsx": () => import("../components/mockups/tenant-dashboard-variants/BoldNeon.tsx"),
  "./components/mockups/tenant-dashboard-variants/Glass.tsx": () => import("../components/mockups/tenant-dashboard-variants/Glass.tsx"),
  "./components/mockups/tenant-dashboard-variants/LivePreview.tsx": () => import("../components/mockups/tenant-dashboard-variants/LivePreview.tsx"),
  "./components/mockups/tenant-dashboard-variants/Minimal.tsx": () => import("../components/mockups/tenant-dashboard-variants/Minimal.tsx"),
  "./components/mockups/tenant-dashboard-variants/Rounded.tsx": () => import("../components/mockups/tenant-dashboard-variants/Rounded.tsx"),
  "./components/mockups/tenant-dashboard-variants/SetupProgressPreview.tsx": () => import("../components/mockups/tenant-dashboard-variants/SetupProgressPreview.tsx"),
  "./components/mockups/tenant-dashboard-variants/SidebarPreview.tsx": () => import("../components/mockups/tenant-dashboard-variants/SidebarPreview.tsx"),
  "./components/mockups/tenant-dashboard-variants/SilverEditorial.tsx": () => import("../components/mockups/tenant-dashboard-variants/SilverEditorial.tsx"),
  "./components/mockups/tenant-dashboard-variants/SilverElevated.tsx": () => import("../components/mockups/tenant-dashboard-variants/SilverElevated.tsx"),
  "./components/mockups/tenant-dashboard-variants/SilverTealBold.tsx": () => import("../components/mockups/tenant-dashboard-variants/SilverTealBold.tsx"),
  "./components/mockups/rentflo-concepts/GlassDashboard.tsx": () => import("../components/mockups/rentflo-concepts/GlassDashboard.tsx"),
  "./components/mockups/rentflo-concepts/HeroLanding.tsx": () => import("../components/mockups/rentflo-concepts/HeroLanding.tsx"),
  "./components/mockups/rentflo-concepts/PaymentReceipt.tsx": () => import("../components/mockups/rentflo-concepts/PaymentReceipt.tsx"),
  "./components/mockups/rentflo-concepts/TiltCards.tsx": () => import("../components/mockups/rentflo-concepts/TiltCards.tsx")
};
